import os
import re
import time
import random
import json
import pandas as pd
from multiprocessing import Pool
from datetime import datetime
from playwright.sync_api import sync_playwright, TimeoutError as PWTimeout

# ==============================================================================
#                                 CẤU HÌNH
# ==============================================================================
INPUT_FILENAME = "a.txt"
PROXY_FILENAME = "proxies.txt"
OUTPUT_FOLDER = "cookies_netflix"

MAX_RETRIES = 3
MAX_CONCURRENT_PROCESSES = 10
WAIT_OTP_TIMEOUT = 15000

# Link lấy mã đăng nhập mới. Trang này chỉ cần điền email và bấm nút lấy mã.
ACCESS_INFO_URL = "https://zx4nxt_bot_1.opomail.store/login?key=e9ebba329687"

# ==============================================================================
#                             CÁC HÀM HỖ TRỢ
# ==============================================================================

def convert_to_netscape_format(cookies: list) -> str:
    """Chuyển đổi list cookie JSON sang định dạng Netscape"""
    lines = ["# Netscape HTTP Cookie File"]
    lines.append("# This file was generated by Python Script")
    lines.append("") 

    for cookie in cookies:
        domain = cookie.get('domain', '')
        flag = "TRUE" if domain.startswith('.') else "FALSE"
        path = cookie.get('path', '/')
        secure = "TRUE" if cookie.get('secure') else "FALSE"
        
        expires = cookie.get('expires', 0)
        if expires == -1 or expires is None:
             expires = 0
        else:
             expires = int(expires)
             
        name = cookie.get('name', '')
        value = cookie.get('value', '')
        
        lines.append(f"{domain}\t{flag}\t{path}\t{secure}\t{expires}\t{name}\t{value}")
    
    return "\n".join(lines)

def save_txt_backup(email: str, netscape_string: str):
    try:
        os.makedirs(OUTPUT_FOLDER, exist_ok=True)
        safe_email = email.replace("@", "_at_")
        file_path = os.path.join(OUTPUT_FOLDER, f"{safe_email}.txt")
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(netscape_string)
    except Exception as e:
        print(f"⚠️ Lỗi lưu backup {email}: {e}")

def read_lines_from_file(filename: str):
    if not os.path.exists(filename):
        print(f"⚠️ Không tìm thấy file '{filename}'. Đang tạo file rỗng...")
        with open(filename, "w", encoding="utf-8") as f:
            f.write("")
        return []
    with open(filename, "r", encoding="utf-8") as f:
        lines = [line.strip() for line in f if line.strip()]
    return list(set(lines)) if filename == INPUT_FILENAME else lines

def parse_proxy(proxy_str: str):
    if not proxy_str:
        return None
    parts = proxy_str.split(':')
    if len(parts) == 2:
        return {"server": f"http://{parts[0]}:{parts[1]}"}
    elif len(parts) == 4:
        return {
            "server": f"http://{parts[0]}:{parts[1]}",
            "username": parts[2],
            "password": parts[3]
        }
    return None

def _extract_netflix_message_pw(page) -> str | None:
    selectors = [
        "div[data-uia='UIMessage-content']",
        "div.ui-message-container",
        "div[role='alert']",
        "div.alert-error",
    ]
    for css in selectors:
        try:
            loc = page.locator(css).first
            if loc.count() > 0:
                return (loc.inner_text(timeout=500) or "").strip()
        except:
            pass
    return None

# --- CHECK PROFILE KHÓA/MỞ ---
def check_profiles_status(page):
    try:
        try:
            page.wait_for_selector("ul.choose-profile", timeout=5000)
        except:
            return "Không tìm thấy danh sách profile"

        profiles = page.locator("li.profile").all()
        if not profiles:
            return "Không có profile nào"

        open_profiles = []
        locked_count = 0

        for p in profiles:
            try:
                name = p.locator(".profile-name").inner_text()
                if p.locator(".svg-icon-profile-lock").is_visible():
                    locked_count += 1
                else:
                    open_profiles.append(name)
            except:
                continue
        
        if open_profiles:
            return f"MỞ: {', '.join(open_profiles)} | KHÓA: {locked_count}"
        elif locked_count > 0:
            return f"FULL KHÓA ({locked_count} profiles)"
        else:
            return "Check lại (Không xác định trạng thái)"
            
    except Exception as e:
        return f"Lỗi check profile: {str(e)}"

# ==============================================================================
#                           LOGIC CHÍNH NETFLIX & LẤY MÃ
# ==============================================================================

def netflix_continue_wait_otp(page, email: str):
    try:
        page.goto("https://www.netflix.com/vn/login", wait_until="domcontentloaded")
        
        page.locator("input[name='userLoginId']").fill(email)
        page.locator("button[data-uia='continue-button']").first.click()

        print(f"⏳ {email}: Đang chờ ô nhập mã xuất hiện...")
        
        try:
            otp_input = page.locator("input[name='challengeOtp']").first
            otp_input.wait_for(state="visible", timeout=WAIT_OTP_TIMEOUT)
            return True, None
        except PWTimeout:
            if page.locator("input[name='password']").is_visible():
                return False, "SKIPPED: Mail yêu cầu mật khẩu"
            msg = _extract_netflix_message_pw(page)
            if msg:
                return False, f"SKIPPED: Lỗi Netflix ({msg})"
            return False, "SKIPPED: Không hiện ô nhập mã (Timeout)"

    except Exception as e:
        return False, f"Error: {str(e)}"

def access_info_prepare_search(access_page, email: str):
    """Mở trang lấy mã mới và điền sẵn email cần tìm mã đăng nhập."""
    try:
        access_page.goto(ACCESS_INFO_URL, wait_until="domcontentloaded")

        email_input = access_page.locator("#email-input").or_(
            access_page.locator("input[type='email']")
        ).first
        email_input.wait_for(state="visible", timeout=15000)
        email_input.click(force=True)
        email_input.fill(email)

        fetch_button = access_page.locator("#btn-fetch").or_(
            access_page.locator("button:has-text('Retrieve Access Info')")
        ).first
        fetch_button.wait_for(state="visible", timeout=10000)
        print(f"✅ {email}: Đã mở trang lấy mã mới và điền email.")

    except Exception as e:
        print(f"⚠️ {email}: Lỗi chuẩn bị trang lấy mã ({e})")

def _extract_login_code_from_access_page(access_page) -> str | None:
    """Lấy chuỗi số mã đăng nhập từ nội dung hiển thị sau khi bấm nút."""
    candidate_selectors = [
        "#result",
        "#results",
        "#access-info",
        "#code",
        "[data-code]",
        ".result",
        ".results",
        ".code",
        ".alert",
        ".message",
        ".card",
    ]

    for selector in candidate_selectors:
        try:
            loc = access_page.locator(selector).first
            if loc.count() > 0 and loc.is_visible(timeout=500):
                text = (loc.inner_text(timeout=1000) or "").strip()
                code = _extract_code_digits(text)
                if code:
                    return code
        except Exception:
            pass

    try:
        body_text = access_page.locator("body").inner_text(timeout=1000)
        return _extract_code_digits(body_text)
    except Exception:
        return None

def _extract_code_digits(text: str | None) -> str | None:
    if not text:
        return None

    # Ưu tiên mã OTP 4-8 chữ số nằm độc lập để tránh dính số từ nội dung khác.
    matches = re.findall(r"(?<!\d)\d{4,8}(?!\d)", text)
    if matches:
        return matches[-1]

    digits = re.sub(r"\D+", "", text)
    if len(digits) >= 4:
        return digits
    return None

def get_and_paste_code_until_browse(netflix_page, access_page) -> bool:
    try:
        access_page.locator("#btn-fetch").or_(
            access_page.locator("button:has-text('Retrieve Access Info')")
        ).first.click()
    except Exception:
        return False

    code_digits = None
    deadline = time.time() + 15
    while time.time() < deadline:
        code_digits = _extract_login_code_from_access_page(access_page)
        if code_digits and len(code_digits) >= 4:
            break
        time.sleep(1)

    if not code_digits or len(code_digits) < 4:
        return False

    otp = netflix_page.locator("input[name='challengeOtp']").first
    if otp.is_visible():
        otp.fill(code_digits)
        try:
            otp.press("Enter", timeout=1000)
        except:
            pass
    else:
        return False

    try:
        netflix_page.wait_for_url(re.compile(r".*/browse.*", re.I), timeout=45000)
        return True
    except:
        return False

# ==============================================================================
#                               WORKER PROCESS
# ==============================================================================

def _login_once_to_browse(data_package):
    email, proxy_str = data_package
    
    result = {
        "Email": email,
        "Status": "Failed",
        "Note": "",
        "Profile_Info": "",
        "Cookie_Netscape": "",
        "Proxy_Used": proxy_str if proxy_str else "Direct"
    }

    proxy_config = parse_proxy(proxy_str)

    try:
        with sync_playwright() as p:
            launch_args = {
                "headless": True,
                "channel": "chrome",
                "args": [
                    "--start-maximized",
                    "--disable-blink-features=AutomationControlled",
                    "--disable-infobars",
                    "--no-sandbox"
                ]
            }
            if proxy_config:
                launch_args["proxy"] = proxy_config

            browser = p.chromium.launch(**launch_args)
            
            context = browser.new_context(
                viewport=None, 
                locale="vi-VN",
                user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
            )
            context.add_init_script("Object.defineProperty(navigator, 'webdriver', {get: () => undefined})")

            netflix_page = context.new_page()

            if proxy_str:
                print(f"🌍 {email}: Đang chạy với Proxy {proxy_str}")

            ok, msg = netflix_continue_wait_otp(netflix_page, email)
            if not ok:
                print(f"❌ {email}: {msg}")
                # --- SỬA ĐỔI: NẾU LỖI TIMEOUT THÌ ĐÁNH DẤU LƯU ---
                if "Timeout" in msg or "Target closed" in msg:
                    result["Status"] = "ProxyError" # Đặt trạng thái riêng
                    result["Note"] = "proxy có vấn đề kiểm tra sau"
                else:
                    result["Note"] = msg
                # -------------------------------------------------
                browser.close()
                return result

            # Khởi tạo tab lấy mã đăng nhập mới và điền email
            access_page = context.new_page()
            access_info_prepare_search(access_page, email)

            for i in range(MAX_RETRIES):
                print(f"🔄 {email}: Thử code lần {i+1}...")
                
                if get_and_paste_code_until_browse(netflix_page, access_page):
                    print(f"✅ {email}: ĐÃ VÀO /browse. Đang check profile...")
                    
                    # 1. Check Profile
                    profile_status = check_profiles_status(netflix_page)
                    print(f"🔎 {email} Profiles: {profile_status}")
                    result["Profile_Info"] = profile_status
                    
                    # 2. Check Payment Status
                    final_note = "OK"
                    try:
                        print(f"💳 {email}: Checking payment URL...")
                        netflix_page.goto("https://www.netflix.com/simplemember/retrypayment")
                        time.sleep(3)
                        
                        current_url = netflix_page.url
                        if "retrypayment" in current_url:
                            final_note = "Tài khoản hết hạn"
                            print(f"⚠️ {email}: Hết hạn thanh toán.")
                        else:
                            final_note = "OK"
                            
                    except Exception as e:
                        print(f"⚠️ {email}: Lỗi check payment - {e}")
                        final_note = "Lỗi check payment"

                    cookies_json = context.cookies()
                    netscape_str = convert_to_netscape_format(cookies_json)
                    save_txt_backup(email, netscape_str)

                    result["Status"] = "Success"
                    result["Note"] = final_note
                    result["Cookie_Netscape"] = netscape_str

                    time.sleep(1)
                    browser.close()
                    return result
                
                time.sleep(5)

            print(f"❌ {email}: Hết số lần thử code.")
            result["Note"] = "Max retries reached"
            browser.close()
            return result

    except Exception as e:
        print(f"❌ {email}: Lỗi - {e}")
        # Nếu lỗi hệ thống lớn mà có timeout cũng lưu luôn
        if "Timeout" in str(e):
             result["Status"] = "ProxyError"
             result["Note"] = "proxy có vấn đề kiểm tra sau"
        else:
             result["Note"] = str(e)
        return result
    
def worker_process(data_package):
    return _login_once_to_browse(data_package)

# ==============================================================================
#                               MAIN PROGRAM
# ==============================================================================

if __name__ == "__main__":
    emails = read_lines_from_file(INPUT_FILENAME)
    proxies = read_lines_from_file(PROXY_FILENAME)

    if not emails:
        print(f"❌ File '{INPUT_FILENAME}' trống hoặc chưa tạo.")
        raise SystemExit(1)

    print(f"📂 Đã đọc {len(emails)} email.")
    print(f"🌍 Đã đọc {len(proxies)} proxies.")
    
    tasks = []
    for i, email in enumerate(emails):
        if len(proxies) > 0:
            proxy_for_this_mail = proxies[i % len(proxies)]
        else:
            proxy_for_this_mail = None
        tasks.append((email, proxy_for_this_mail))

    print(f"🚀 Bắt đầu chạy đa luồng (Max: {MAX_CONCURRENT_PROCESSES})...")
    print("⚠️  Ấn Ctrl+C để dừng chương trình bất cứ lúc nào.")
    print("---------------------------------------------------------------")

    all_results = []
    
    pool = Pool(processes=MAX_CONCURRENT_PROCESSES)
    try:
        async_result = pool.map_async(worker_process, tasks)
        while not async_result.ready():
            time.sleep(1)
        all_results = async_result.get()
        
    except KeyboardInterrupt:
        print("\n🛑 Đã nhận lệnh dừng (Ctrl+C). Đang hủy các tiến trình con...")
        pool.terminate()
        pool.join()
        print("✅ Đã dừng chương trình an toàn.")
        raise SystemExit(0)
    except Exception as e:
        print(f"❌ Lỗi hệ thống: {e}")
        pool.terminate()
    finally:
        pool.close()
        try:
            pool.join()
        except:
            pass

    print("---------------------------------------------------------------")
    print("💾 Đang xử lý và lưu file Excel...")

    try:
        if all_results:
            df = pd.DataFrame(all_results)
            if "Status" in df.columns:
                # --- SỬA ĐỔI: LỌC CẢ SUCCESS VÀ PROXYERROR ---
                # Lấy những dòng Success HOẶC ProxyError
                df_success = df[df["Status"].isin(["Success", "ProxyError"])]
                
                cols_needed = ["Email", "Status", "Note", "Profile_Info", "Proxy_Used", "Cookie_Netscape"]
                # Lọc cột nếu tồn tại
                final_cols = [c for c in cols_needed if c in df_success.columns]
                
                if not df_success.empty:
                    # Sắp xếp lại cột theo thứ tự cols_needed
                    df_success = df_success[final_cols]
                    
                    thoi_gian = datetime.now().strftime("%Y%m%d_%H%M%S")
                    dynamic_filename = f"Netflix_Accounts_{thoi_gian}.xlsx"
                    df_success.to_excel(dynamic_filename, index=False)
                    print(f"✅ Đã xuất {len(df_success)} tài khoản (bao gồm lỗi proxy) ra file: {dynamic_filename}")
                else:
                    print("⚠️ Không có tài khoản nào cần lưu.")
            else:
                print("⚠️ Dữ liệu trả về thiếu cột Status.")
        else:
            print("⚠️ Không có dữ liệu trả về.")
    except Exception as e:
        print(f"❌ Lỗi ghi file Excel: {e}")